//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORCAMENTOS_FOCKINK.Representantes {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Representantes.RepresentantesSoap")]
    public interface RepresentantesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since message validaLoginRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validaLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ORCAMENTOS_FOCKINK.Representantes.validaLoginResponse validaLogin(ORCAMENTOS_FOCKINK.Representantes.validaLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validaLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.validaLoginResponse> validaLoginAsync(ORCAMENTOS_FOCKINK.Representantes.validaLoginRequest request);
        
        // CODEGEN: Generating message contract since message listaClientesRepresentanteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaClientesRepresentante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteResponse listaClientesRepresentante(ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaClientesRepresentante", ReplyAction="*")]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteResponse> listaClientesRepresentanteAsync(ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteRequest request);
        
        // CODEGEN: Generating message contract since message listaContatosClientesRepresentanteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaContatosClientesRepresentante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteResponse listaContatosClientesRepresentante(ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaContatosClientesRepresentante", ReplyAction="*")]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteResponse> listaContatosClientesRepresentanteAsync(ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteRequest request);
        
        // CODEGEN: Generating message contract since message listaEmpresaUsuarioSOEFRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaEmpresaUsuarioSOEF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFResponse listaEmpresaUsuarioSOEF(ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaEmpresaUsuarioSOEF", ReplyAction="*")]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFResponse> listaEmpresaUsuarioSOEFAsync(ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFRequest request);
        
        // CODEGEN: Generating message contract since message listaIndicadorNegocioRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaIndicadorNegocio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioResponse listaIndicadorNegocio(ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaIndicadorNegocio", ReplyAction="*")]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioResponse> listaIndicadorNegocioAsync(ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioRequest request);
        
        // CODEGEN: Generating message contract since message listaTipoNegocioRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaTipoNegocio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioResponse listaTipoNegocio(ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaTipoNegocio", ReplyAction="*")]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioResponse> listaTipoNegocioAsync(ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioRequest request);
        
        // CODEGEN: Generating message contract since message listaEventoPagamentoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaEventoPagamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoResponse listaEventoPagamento(ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaEventoPagamento", ReplyAction="*")]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoResponse> listaEventoPagamentoAsync(ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoRequest request);
        
        // CODEGEN: Generating message contract since message listaDomobrRefCodesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaDomobrRefCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesResponse listaDomobrRefCodes(ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaDomobrRefCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesResponse> listaDomobrRefCodesAsync(ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Seguranca : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string senhaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("Senha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class validaLoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string senha;
        
        public validaLoginRequest() {
        }
        
        public validaLoginRequest(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string usuario, string senha) {
            this.Seguranca = Seguranca;
            this.usuario = usuario;
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class validaLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string validaLoginResult;
        
        public validaLoginResponse() {
        }
        
        public validaLoginResponse(string validaLoginResult) {
            this.validaLoginResult = validaLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaClientesRepresentante", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaClientesRepresentanteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string empresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string codRepresentante;
        
        public listaClientesRepresentanteRequest() {
        }
        
        public listaClientesRepresentanteRequest(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string empresa, string codRepresentante) {
            this.Seguranca = Seguranca;
            this.empresa = empresa;
            this.codRepresentante = codRepresentante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaClientesRepresentanteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaClientesRepresentanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet listaClientesRepresentanteResult;
        
        public listaClientesRepresentanteResponse() {
        }
        
        public listaClientesRepresentanteResponse(System.Data.DataSet listaClientesRepresentanteResult) {
            this.listaClientesRepresentanteResult = listaClientesRepresentanteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaContatosClientesRepresentante", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaContatosClientesRepresentanteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string empresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string codRepresentante;
        
        public listaContatosClientesRepresentanteRequest() {
        }
        
        public listaContatosClientesRepresentanteRequest(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string empresa, string codRepresentante) {
            this.Seguranca = Seguranca;
            this.empresa = empresa;
            this.codRepresentante = codRepresentante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaContatosClientesRepresentanteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaContatosClientesRepresentanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet listaContatosClientesRepresentanteResult;
        
        public listaContatosClientesRepresentanteResponse() {
        }
        
        public listaContatosClientesRepresentanteResponse(System.Data.DataSet listaContatosClientesRepresentanteResult) {
            this.listaContatosClientesRepresentanteResult = listaContatosClientesRepresentanteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaEmpresaUsuarioSOEF", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaEmpresaUsuarioSOEFRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string usuario;
        
        public listaEmpresaUsuarioSOEFRequest() {
        }
        
        public listaEmpresaUsuarioSOEFRequest(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string usuario) {
            this.Seguranca = Seguranca;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaEmpresaUsuarioSOEFResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaEmpresaUsuarioSOEFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet listaEmpresaUsuarioSOEFResult;
        
        public listaEmpresaUsuarioSOEFResponse() {
        }
        
        public listaEmpresaUsuarioSOEFResponse(System.Data.DataSet listaEmpresaUsuarioSOEFResult) {
            this.listaEmpresaUsuarioSOEFResult = listaEmpresaUsuarioSOEFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaIndicadorNegocio", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaIndicadorNegocioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string empresa;
        
        public listaIndicadorNegocioRequest() {
        }
        
        public listaIndicadorNegocioRequest(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string empresa) {
            this.Seguranca = Seguranca;
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaIndicadorNegocioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaIndicadorNegocioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet listaIndicadorNegocioResult;
        
        public listaIndicadorNegocioResponse() {
        }
        
        public listaIndicadorNegocioResponse(System.Data.DataSet listaIndicadorNegocioResult) {
            this.listaIndicadorNegocioResult = listaIndicadorNegocioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaTipoNegocio", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaTipoNegocioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca;
        
        public listaTipoNegocioRequest() {
        }
        
        public listaTipoNegocioRequest(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca) {
            this.Seguranca = Seguranca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaTipoNegocioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaTipoNegocioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet listaTipoNegocioResult;
        
        public listaTipoNegocioResponse() {
        }
        
        public listaTipoNegocioResponse(System.Data.DataSet listaTipoNegocioResult) {
            this.listaTipoNegocioResult = listaTipoNegocioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaEventoPagamento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaEventoPagamentoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca;
        
        public listaEventoPagamentoRequest() {
        }
        
        public listaEventoPagamentoRequest(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca) {
            this.Seguranca = Seguranca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaEventoPagamentoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaEventoPagamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet listaEventoPagamentoResult;
        
        public listaEventoPagamentoResponse() {
        }
        
        public listaEventoPagamentoResponse(System.Data.DataSet listaEventoPagamentoResult) {
            this.listaEventoPagamentoResult = listaEventoPagamentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaDomobrRefCodes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaDomobrRefCodesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rvDomain;
        
        public listaDomobrRefCodesRequest() {
        }
        
        public listaDomobrRefCodesRequest(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string rvDomain) {
            this.Seguranca = Seguranca;
            this.rvDomain = rvDomain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaDomobrRefCodesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listaDomobrRefCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet listaDomobrRefCodesResult;
        
        public listaDomobrRefCodesResponse() {
        }
        
        public listaDomobrRefCodesResponse(System.Data.DataSet listaDomobrRefCodesResult) {
            this.listaDomobrRefCodesResult = listaDomobrRefCodesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RepresentantesSoapChannel : ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepresentantesSoapClient : System.ServiceModel.ClientBase<ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap>, ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap {
        
        public RepresentantesSoapClient() {
        }
        
        public RepresentantesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepresentantesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepresentantesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepresentantesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ORCAMENTOS_FOCKINK.Representantes.validaLoginResponse ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.validaLogin(ORCAMENTOS_FOCKINK.Representantes.validaLoginRequest request) {
            return base.Channel.validaLogin(request);
        }
        
        public string validaLogin(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string usuario, string senha) {
            ORCAMENTOS_FOCKINK.Representantes.validaLoginRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.validaLoginRequest();
            inValue.Seguranca = Seguranca;
            inValue.usuario = usuario;
            inValue.senha = senha;
            ORCAMENTOS_FOCKINK.Representantes.validaLoginResponse retVal = ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).validaLogin(inValue);
            return retVal.validaLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.validaLoginResponse> ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.validaLoginAsync(ORCAMENTOS_FOCKINK.Representantes.validaLoginRequest request) {
            return base.Channel.validaLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.validaLoginResponse> validaLoginAsync(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string usuario, string senha) {
            ORCAMENTOS_FOCKINK.Representantes.validaLoginRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.validaLoginRequest();
            inValue.Seguranca = Seguranca;
            inValue.usuario = usuario;
            inValue.senha = senha;
            return ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).validaLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteResponse ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaClientesRepresentante(ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteRequest request) {
            return base.Channel.listaClientesRepresentante(request);
        }
        
        public System.Data.DataSet listaClientesRepresentante(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string empresa, string codRepresentante) {
            ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteRequest();
            inValue.Seguranca = Seguranca;
            inValue.empresa = empresa;
            inValue.codRepresentante = codRepresentante;
            ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteResponse retVal = ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaClientesRepresentante(inValue);
            return retVal.listaClientesRepresentanteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteResponse> ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaClientesRepresentanteAsync(ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteRequest request) {
            return base.Channel.listaClientesRepresentanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteResponse> listaClientesRepresentanteAsync(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string empresa, string codRepresentante) {
            ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaClientesRepresentanteRequest();
            inValue.Seguranca = Seguranca;
            inValue.empresa = empresa;
            inValue.codRepresentante = codRepresentante;
            return ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaClientesRepresentanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteResponse ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaContatosClientesRepresentante(ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteRequest request) {
            return base.Channel.listaContatosClientesRepresentante(request);
        }
        
        public System.Data.DataSet listaContatosClientesRepresentante(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string empresa, string codRepresentante) {
            ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteRequest();
            inValue.Seguranca = Seguranca;
            inValue.empresa = empresa;
            inValue.codRepresentante = codRepresentante;
            ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteResponse retVal = ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaContatosClientesRepresentante(inValue);
            return retVal.listaContatosClientesRepresentanteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteResponse> ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaContatosClientesRepresentanteAsync(ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteRequest request) {
            return base.Channel.listaContatosClientesRepresentanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteResponse> listaContatosClientesRepresentanteAsync(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string empresa, string codRepresentante) {
            ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaContatosClientesRepresentanteRequest();
            inValue.Seguranca = Seguranca;
            inValue.empresa = empresa;
            inValue.codRepresentante = codRepresentante;
            return ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaContatosClientesRepresentanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFResponse ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaEmpresaUsuarioSOEF(ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFRequest request) {
            return base.Channel.listaEmpresaUsuarioSOEF(request);
        }
        
        public System.Data.DataSet listaEmpresaUsuarioSOEF(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string usuario) {
            ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFRequest();
            inValue.Seguranca = Seguranca;
            inValue.usuario = usuario;
            ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFResponse retVal = ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaEmpresaUsuarioSOEF(inValue);
            return retVal.listaEmpresaUsuarioSOEFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFResponse> ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaEmpresaUsuarioSOEFAsync(ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFRequest request) {
            return base.Channel.listaEmpresaUsuarioSOEFAsync(request);
        }
        
        public System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFResponse> listaEmpresaUsuarioSOEFAsync(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string usuario) {
            ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaEmpresaUsuarioSOEFRequest();
            inValue.Seguranca = Seguranca;
            inValue.usuario = usuario;
            return ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaEmpresaUsuarioSOEFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioResponse ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaIndicadorNegocio(ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioRequest request) {
            return base.Channel.listaIndicadorNegocio(request);
        }
        
        public System.Data.DataSet listaIndicadorNegocio(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string empresa) {
            ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioRequest();
            inValue.Seguranca = Seguranca;
            inValue.empresa = empresa;
            ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioResponse retVal = ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaIndicadorNegocio(inValue);
            return retVal.listaIndicadorNegocioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioResponse> ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaIndicadorNegocioAsync(ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioRequest request) {
            return base.Channel.listaIndicadorNegocioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioResponse> listaIndicadorNegocioAsync(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string empresa) {
            ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaIndicadorNegocioRequest();
            inValue.Seguranca = Seguranca;
            inValue.empresa = empresa;
            return ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaIndicadorNegocioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioResponse ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaTipoNegocio(ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioRequest request) {
            return base.Channel.listaTipoNegocio(request);
        }
        
        public System.Data.DataSet listaTipoNegocio(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca) {
            ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioRequest();
            inValue.Seguranca = Seguranca;
            ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioResponse retVal = ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaTipoNegocio(inValue);
            return retVal.listaTipoNegocioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioResponse> ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaTipoNegocioAsync(ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioRequest request) {
            return base.Channel.listaTipoNegocioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioResponse> listaTipoNegocioAsync(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca) {
            ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaTipoNegocioRequest();
            inValue.Seguranca = Seguranca;
            return ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaTipoNegocioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoResponse ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaEventoPagamento(ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoRequest request) {
            return base.Channel.listaEventoPagamento(request);
        }
        
        public System.Data.DataSet listaEventoPagamento(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca) {
            ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoRequest();
            inValue.Seguranca = Seguranca;
            ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoResponse retVal = ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaEventoPagamento(inValue);
            return retVal.listaEventoPagamentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoResponse> ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaEventoPagamentoAsync(ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoRequest request) {
            return base.Channel.listaEventoPagamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoResponse> listaEventoPagamentoAsync(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca) {
            ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaEventoPagamentoRequest();
            inValue.Seguranca = Seguranca;
            return ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaEventoPagamentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesResponse ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaDomobrRefCodes(ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesRequest request) {
            return base.Channel.listaDomobrRefCodes(request);
        }
        
        public System.Data.DataSet listaDomobrRefCodes(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string rvDomain) {
            ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesRequest();
            inValue.Seguranca = Seguranca;
            inValue.rvDomain = rvDomain;
            ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesResponse retVal = ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaDomobrRefCodes(inValue);
            return retVal.listaDomobrRefCodesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesResponse> ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap.listaDomobrRefCodesAsync(ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesRequest request) {
            return base.Channel.listaDomobrRefCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesResponse> listaDomobrRefCodesAsync(ORCAMENTOS_FOCKINK.Representantes.Seguranca Seguranca, string rvDomain) {
            ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesRequest inValue = new ORCAMENTOS_FOCKINK.Representantes.listaDomobrRefCodesRequest();
            inValue.Seguranca = Seguranca;
            inValue.rvDomain = rvDomain;
            return ((ORCAMENTOS_FOCKINK.Representantes.RepresentantesSoap)(this)).listaDomobrRefCodesAsync(inValue);
        }
    }
}
